# alertmanager.service — rendered from services/alertmanager.service.tpl by
# install-alertmanager.sh. Do not edit this file; edit the template and
# re-run the installer.
#
# Tokens rendered:  {{LISTEN}}  (from environment.yml: alertmanager_listen)

[Unit]
Description=Alertmanager — Alert routing and notification
Documentation=https://prometheus.io/docs/alerting/latest/alertmanager/
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
User=alertmanager
Group=alertmanager
ExecStart=/usr/local/bin/alertmanager \
    --config.file=/etc/alertmanager/alertmanager.yml \
    --storage.path=/var/lib/alertmanager \
    --web.listen-address={{LISTEN}} \
    --cluster.advertise-address={{LISTEN}}
ExecReload=/bin/kill -HUP $MAINPID
Restart=on-failure
RestartSec=5s
TimeoutStopSec=20s

# Hardening
NoNewPrivileges=yes
ProtectSystem=strict
ProtectHome=yes
PrivateTmp=yes
PrivateDevices=yes
ProtectKernelTunables=yes
ProtectControlGroups=yes
ReadWritePaths=/var/lib/alertmanager /var/log/monitoring

[Install]
WantedBy=multi-user.target
